//generated by claude

// Service Worker: JSON to HTML Stream Converter
// Install and activate immediately
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Intercept fetch requests
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  
  // Only intercept requests that might return JSON
  // Skip service worker script itself and other assets
  if (event.request.method !== 'GET' || 
      url.pathname.endsWith('.js') || 
      url.pathname.endsWith('.css') ||
      url.pathname.endsWith('.png') ||
      url.pathname.endsWith('.jpg') ||
      url.pathname === '/sw.js') {
    return;
  }

  event.respondWith(handleFetch(event.request));
});

async function handleFetch(request) {
  try {
    const response = await fetch(request);
    const contentType = response.headers.get('content-type') || '';
    
    // Check if response is JSON
    if (contentType.includes('application/json')) {
      return convertJsonToHtmlStream(response);
    }
    
    // Return original response if not JSON
    return response;
  } catch (error) {
    console.error('Fetch error:', error);
    return new Response('Fetch failed', { status: 500 });
  }
}

async function convertJsonToHtmlStream(response) {
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let jsonBuffer = '';
  
  const stream = new ReadableStream({
    async start(controller) {
      // Send HTML header
      controller.enqueue(new TextEncoder().encode(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>JSON Response</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    .container {
      background: white;
      border-radius: 8px;
      padding: 24px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 {
      color: #333;
      margin-top: 0;
    }
    pre {
      background: #f8f8f8;
      border: 1px solid #ddd;
      border-radius: 4px;
      padding: 16px;
      overflow-x: auto;
    }
    .json-key {
      color: #881391;
    }
    .json-string {
      color: #1A7F37;
    }
    .json-number {
      color: #0550AE;
    }
    .json-boolean {
      color: #CF222E;
    }
    .json-null {
      color: #6E7781;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>JSON Response</h1>
    <pre id="json-content">
      `));

      try {
        // Read the entire JSON response
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          jsonBuffer += decoder.decode(value, { stream: true });
        }
        
        // Parse and format JSON
        const jsonData = JSON.parse(jsonBuffer);
        const formattedJson = syntaxHighlight(JSON.stringify(jsonData, null, 2));
        
        // Send formatted JSON
        controller.enqueue(new TextEncoder().encode(formattedJson));
        
      } catch (error) {
        // If JSON parsing fails, send the raw content
        controller.enqueue(new TextEncoder().encode(
          `<span style="color: red;">Error parsing JSON:</span>\n${jsonBuffer}`
        ));
      }
      
      // Send HTML footer
      controller.enqueue(new TextEncoder().encode(`
    </pre>
  </div>
</body>
</html>
      `));
      
      controller.close();
    }
  });
  
  return new Response(stream, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
    }
  });
}

// Syntax highlighting for JSON
function syntaxHighlight(json) {
  json = json.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return json.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, (match) => {
    let cls = 'json-number';
    if (/^"/.test(match)) {
      if (/:$/.test(match)) {
        cls = 'json-key';
      } else {
        cls = 'json-string';
      }
    } else if (/true|false/.test(match)) {
      cls = 'json-boolean';
    } else if (/null/.test(match)) {
      cls = 'json-null';
    }
    return '<span class="' + cls + '">' + match + '</span>';
  });
}